AWSTemplateFormatVersion: "2010-09-09"
Description: "Create Customer Gateway, VPN Connection and configure TGW associations/propagations for an existing Transit Gateway. (TGW, TGW RTB, VPC Attachments, RAM Shares are NOT managed by this template)"

Parameters:
  # --- Customer Gateway Parameters ---
  CustomerGatewayIpAddress:
    Type: String
    Description: "[Do not change]Specify the IP address of the on-premise router. It is specified in the HOTnet service."
    Default: "172.22.65.18" # 例: オンプレミスルーターのIPアドレスを指定
  CustomerGatewayBgpAsn:
    Type: Number
    Default: 65000
    Description: "[Do not change]Customer gateway BGP AS number"
  CustomerGatewayName:
    Type: String
    Default: "dx-tgw-vpn01-cgw01" # 元のテンプレートの値
    Description: "The name of your customer gateway"

  # --- VPN Connection Parameters ---
  VpnConnectionName:
    Type: String
    Default: "dx-tgw-s2s01" # 元のテンプレートの値
    Description: "The name of the VPN connection"

  # --- Existing Transit Gateway Infrastructure Parameters ---
  ExistingTransitGatewayId:
    Type: String
    Default: "tgw-0073091495d122b11"
    Description: "[Required] Existing Transit Gateway ID (e.g., tgw-xxxxxxxxxxxxxxxxx)."

  ExistingTgwRouteTableIdForVpnAssociation:
    Type: String
    Default: "tgw-rtb-0c350530e716b4136"
    Description: "[Required] Existing TGW route table ID to associate the VPN connection with (for communication from on-premise)"

  ExistingTgwRouteTableIdForVpnPropagation:
    Type: String
    Default: "tgw-rtb-0228b4236053ed018"
    Description: "[Required] Existing TGW route table ID to propagate VPN route (for communication to on-premise)"

  # --- Optional Static Route Parameters (Uncomment if needed) ---
  # StaticRouteDestinationCidr:
  #   Type: String
  #   Description: "(Optional) Destination CIDR for static route via VPN (e.g., 0.0.0.0/0 or specific on-prem CIDR). Leave blank if using BGP or no static route needed from TGW."
  #   Default: ""
  # ExistingTgwRouteTableIdForStaticRoute:
  #   Type: String
  #   Description: "(Optional) ID of the TGW Route Table to add the static route. If blank and StaticRouteDestinationCidr is set, propagation table ID will be used."
  #   Default: ""

# --- Optional Conditions for Static Route (Uncomment if needed) ---
# Conditions:
#  CreateStaticRoute: !Not [!Equals [!Ref StaticRouteDestinationCidr, ""]]
#  UseSeparateStaticRouteTable: !And
#    - !Condition CreateStaticRoute
#    - !Not [!Equals [!Ref ExistingTgwRouteTableIdForStaticRoute, ""]]

Resources:
  # --- VPN Connection ---
  EC2VPNConnection:
    Type: "AWS::EC2::VPNConnection"
    Properties:
      Type: "ipsec.1"
      # BGPを使用しない静的ルートVPNの場合は true に設定
      StaticRoutesOnly: false
      CustomerGatewayId: !Ref EC2CustomerGateway
      # 既存のTransit Gateway IDを参照
      TransitGatewayId: !Ref ExistingTransitGatewayId
      Tags:
        - Key: "Name"
          Value: !Ref VpnConnectionName
    # 既存のTGWを参照するため、DependsOnは不要

  # --- Transit Gateway Route Table Association for VPN ---
  # 作成したVPN接続を指定された既存TGWルートテーブルに関連付ける
  TgwRouteTableAssociationVpn:
    Type: "AWS::EC2::TransitGatewayRouteTableAssociation"
    Properties:
      # 作成したVPN Connectionのリソースを参照
      TransitGatewayAttachmentId: !Ref EC2VPNConnection
      # パラメータで指定された既存TGWルートテーブルIDを参照
      TransitGatewayRouteTableId: !Ref ExistingTgwRouteTableIdForVpnAssociation
    # VPN Connection作成後に実行
    DependsOn: EC2VPNConnection

  # --- Transit Gateway Route Table Propagation for VPN ---
  # 作成したVPN接続からの経路(BGP)を指定された既存TGWルートテーブルに伝播させる
  TgwRouteTablePropagationVpn:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      # 作成したVPN Connectionのリソースを参照
      TransitGatewayAttachmentId: !Ref EC2VPNConnection
      # パラメータで指定された既存TGWルートテーブルIDを参照
      TransitGatewayRouteTableId: !Ref ExistingTgwRouteTableIdForVpnPropagation
    # VPN Connection作成後に実行
    DependsOn: EC2VPNConnection

  # --- Optional: Transit Gateway Static Route via VPN (Uncomment and configure if needed) ---
  # TgwStaticRouteViaVpn:
  #   Condition: CreateStaticRoute # 静的ルートCIDRが指定された場合のみ作成
  #   Type: "AWS::EC2::TransitGatewayRoute"
  #   Properties:
  #     DestinationCidrBlock: !Ref StaticRouteDestinationCidr
  #     TransitGatewayAttachmentId: !Ref EC2VPNConnection # このVPN接続を経路とする
  #     TransitGatewayRouteTableId: !If # 静的ルート用テーブルが指定されていればそれを使用、なければ伝播用テーブルを使用
  #       - UseSeparateStaticRouteTable
  #       - !Ref ExistingTgwRouteTableIdForStaticRoute
  #       - !Ref ExistingTgwRouteTableIdForVpnPropagation
  #   DependsOn: TgwRouteTablePropagationVpn # 伝播設定後にルート追加 (依存関係は適宜調整)

Outputs:
  VpnConnectionId:
    Description: "ID of the created VPN Connection"
    Value: !Ref EC2VPNConnection
  CustomerGatewayId:
    Description: "ID of the created Customer Gateway"
    Value: !Ref EC2CustomerGateway
  # --- Optional: Add outputs for tunnel IPs if needed ---
  # VpnConnectionTunnel1IpAddress:
  #   Description: "Outside IP Address for VPN Tunnel 1"
  #   Value: !GetAtt EC2VPNConnection.TunnelOptions.0.OutsideIpAddress
  # VpnConnectionTunnel2IpAddress:
  #   Description: "Outside IP Address for VPN Tunnel 2"
  #   Value: !GetAtt EC2VPNConnection.TunnelOptions.1.OutsideIpAddress