AWSTemplateFormatVersion: "2010-09-09"
Description: "Create Customer Gateway (with Private IP for DX+VPN), VPN Connection over Direct Connect Transit VIF, and configure TGW associations/propagations."

Parameters:
  # --- Customer Gateway Parameters (for DX+VPN, use Private IP) ---
  CustomerGatewayIpAddress:
    Type: String
    Default: "172.22.65.18" # 重要: Direct Connect経由で接続するオンプレミスルーターの「プライベートIPアドレス」を指定してください
    Description: "[Required] Specify the Private IP address of the on-premise router connected via Direct Connect."
    MinLength: 1
  CustomerGatewayBgpAsn:
    Type: Number
    Default: 65000
    Description: "[Required] Customer gateway BGP AS number."
  CustomerGatewayName:
    Type: String
    Default: "dx-tgw-vpn01-cgw01" # 必要に応じてカスタマイズしてください
    Description: "The name for the Customer Gateway."

  # --- VPN Connection Parameters ---
  VpnConnectionName:
    Type: String
    Default: "dx-tgw-s2s01"
    Description: "The name of the VPN connection."

  # --- Existing Infrastructure Parameters ---
  ExistingTransitGatewayId:
    Type: String
    Default: "tgw-0073091495d122b11"
    Description: "[Required] Existing Transit Gateway ID."
    MinLength: 1
  ExistingTransportTransitGatewayAttachmentId:
    Type: String
    Default: "tgw-attach-07f729a9452de7926" # 前回の指定に基づくデフォルト値
    Description: "[Required] Existing Transport Transit Gateway Attachment ID (Transit VIF attachment)."
    MinLength: 1
  ExistingTgwRouteTableIdForVpnAssociation:
    Type: String
    Default: "tgw-rtb-0c350530e716b4136" # 元のテンプレートの値
    Description: "[Required] Existing TGW route table ID to associate the VPN connection with."
    MinLength: 1
  ExistingTgwRouteTableIdForVpnPropagation:
    Type: String
    Default: "tgw-rtb-0228b4236053ed018" # 元のテンプレートの値
    Description: "[Required] Existing TGW route table ID to propagate VPN route."
    MinLength: 1

Resources:
  # --- Customer Gateway (with Private IP for DX+VPN) ---
  EC2CustomerGateway:
    Type: "AWS::EC2::CustomerGateway"
    Properties:
      BgpAsn: !Ref CustomerGatewayBgpAsn
      IpAddress: !Ref CustomerGatewayIpAddress # パラメータで指定されたプライベートIPを使用
      Type: "ipsec.1"
      Tags:
        - Key: "Name"
          Value: !Ref CustomerGatewayName

  # --- VPN Connection over Direct Connect ---
  EC2VPNConnection:
    Type: "AWS::EC2::VPNConnection"
    Properties:
      Type: "ipsec.1"
      StaticRoutesOnly: false # 動的ルーティング (BGP)
      CustomerGatewayId: !Ref EC2CustomerGateway # このテンプレートで作成するCGWを参照
      TransitGatewayId: !Ref ExistingTransitGatewayId
      TransportTransitGatewayAttachmentId: !Ref ExistingTransportTransitGatewayAttachmentId # Transit VIF Attachment ID を指定
      Tags:
        - Key: "Name"
          Value: !Ref VpnConnectionName
    # !Ref EC2CustomerGateway により、CGW作成後にVPNが作成される依存関係が自動的に設定されます

  # --- Transit Gateway Route Table Association for VPN ---
  TgwRouteTableAssociationVpn:
    Type: "AWS::EC2::TransitGatewayRouteTableAssociation"
    Properties:
      TransitGatewayAttachmentId: !Ref EC2VPNConnection
      TransitGatewayRouteTableId: !Ref ExistingTgwRouteTableIdForVpnAssociation
    DependsOn: EC2VPNConnection # 依存関係を明示（必須ではないが推奨）

  # --- Transit Gateway Route Table Propagation for VPN ---
  TgwRouteTablePropagationVpn:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref EC2VPNConnection
      TransitGatewayRouteTableId: !Ref ExistingTgwRouteTableIdForVpnPropagation
    DependsOn: EC2VPNConnection # 依存関係を明示（必須ではないが推奨）

Outputs:
  VpnConnectionId:
    Description: "ID of the created VPN Connection"
    Value: !Ref EC2VPNConnection
  CustomerGatewayId:
    Description: "ID of the created Customer Gateway"
    Value: !Ref EC2CustomerGateway